version: "3.8"

services:
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "8080:8080"
    command: ["pnpm", "dev"]

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DEBUG: 1
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
